---
- name: Check which PHP variables are set in .htaccess
  ansible.builtin.command: 'grep -Eq "php_value\s+{{ item.key }}" {{ nextcloud_webroot }}/.htaccess'
  with_dict: "{{ nextcloud_php_settings | default({}) }}"
  register: __nextcloud_htaccess_vars
  check_mode: False
  failed_when: False
  changed_when: False

- name: Replace existing PHP variables in .htaccess
  ansible.builtin.replace:
    dest: "{{ nextcloud_webroot }}/.htaccess"
    regexp: '^(\s*)php_value\s+{{ item.key }}.*$'
    replace: '\1php_value {{ item.key }} {{ item.value }}'
  with_items: "{{ __nextcloud_htaccess_vars | json_query(query) }}"
  vars:
    query: "results[?rc == `0`].item"

- name: Add new PHP values to .htaccess
  ansible.builtin.replace:
    dest: "{{ nextcloud_webroot }}/.htaccess"
    regexp: "^(<IfModule mod_php.*)$"
    replace: '\1\n  php_value {{ item.key }} {{ item.value }}'
  with_items: "{{ __nextcloud_htaccess_vars | json_query(query) }}"
  vars:
    query: "results[?rc == `1`].item"

- name: Set PHP variables in .user.ini
  ansible.builtin.lineinfile:
    dest: "{{ nextcloud_webroot }}/.user.ini"
    regexp: "^{{ item.key }}=.*$"
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ nextcloud_php_settings | default({}) }}"
