---
- name: "Nextcloud download: create temporary download directory"
  ansible.builtin.file:
    name: "{{ nextcloud_dl_tmp_dir }}"
    state: directory
    mode: 0755

- name: "Nextcloud download: clone version branch from git repo"
  ansible.builtin.git:
    repo: "{{ nextcloud_repo }}"
    dest: "{{ nextcloud_dl_tmp_dir }}/nextcloud"
    version: "v{{ nextcloud_version }}"
  when: nextcloud_src_type == "git"

- name: "Nextcloud download: Download Nextcloud archive"
  when: nextcloud_src_type == "tar"
  block:
    - name: "Nextcloud download: fetch version tarball and signature"
      ansible.builtin.get_url:
        dest: "{{ nextcloud_dl_tmp_dir }}/{{ item | basename }}"
        url: "{{ item }}"
        mode: "0600"
      with_items:
        - "{{ nextcloud_tar_url }}"
        - "{{ nextcloud_sig_url }}"

    - name: "Nextcloud download: provide upstream signing-key"
      ansible.builtin.copy:
        dest: "{{ nextcloud_dl_tmp_dir }}"
        src: "{{ nextcloud_gpg_key }}.gpg"
        mode: "0600"

    - name: "Nextcloud download: verify signature of tarball"
      args:
        chdir: "{{ nextcloud_dl_tmp_dir }}"
      ansible.builtin.command: >
        gpgv --keyring ./{{ nextcloud_gpg_key }}.gpg
        {{ nextcloud_sig_url | basename }}
        {{ nextcloud_tar_url | basename }}
      changed_when: False

    - name: "Nextcloud download: ensure sane state before extracting tarball"
      ansible.builtin.file:
        path: "{{ nextcloud_dl_tmp_dir }}/nextcloud"
        state: absent

    - name: "Nextcloud download: extract tarball"
      ansible.builtin.unarchive:
        dest: "{{ nextcloud_dl_tmp_dir }}"
        src: "{{ nextcloud_dl_tmp_dir }}/{{ nextcloud_tar_url | basename }}"
        remote_src: yes

- name: "Nextcloud download: adjust owner for installation/upgrade"
  ansible.builtin.file:
    path: "{{ nextcloud_dl_tmp_dir }}"
    state: directory
    owner: "{{ nextcloud_http_user }}"
    group: "{{ nextcloud_http_group }}"
    recurse: yes

- name: "Nextcloud download: check if new version has been downloaded"
  ansible.builtin.stat:
    path: "{{ nextcloud_dl_tmp_dir }}/nextcloud/version.php"
  register: __nextcloud_dl_post

- name: "Nextcloud download: assert that new Nextcloud version got fetched"
  ansible.builtin.assert:
    that:
      - __nextcloud_dl_post.stat.exists
    msg: "Error: Failed to fetch new Nextcloud version"
