---

- name: Create Nextcloud MySQL database
  community.mysql.mysql_db:
    name: "{{ nextcloud_mysql_db }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
  delegate_to: "{{ nextcloud_mysql_host_delegate }}"

- name: Create Nextcloud MySQL database user
  community.mysql.mysql_user:
    name: "{{ nextcloud_mysql_user }}"
    host: "{{ nextcloud_mysql_user_host }}"
    password: "{{ nextcloud_mysql_password }}"
    priv: "{{ nextcloud_mysql_db }}.*:ALL"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
  delegate_to: "{{ nextcloud_mysql_host_delegate }}"
