---
- name: "Nextcloud upgrade: set maintenance mode via occ commandline"
  become: true
  become_user: "{{ nextcloud_http_user }}"
  ansible.builtin.command: php occ maintenance:mode --on
  args:
    chdir: "{{ nextcloud_webroot_old }}"
  changed_when: false

- name: "Nextcloud upgrade: copy config.php over from old instance"
  ansible.builtin.copy:
    src: "{{ nextcloud_webroot_old }}/config/config.php"
    dest: "{{ nextcloud_dl_tmp_dir }}/nextcloud/config/config.php"
    remote_src: yes
    owner: "{{ nextcloud_http_user }}"
    group: "{{ nextcloud_http_group }}"
    mode: 0640

- name: "Nextcloud upgrade: run apps tasks"
  ansible.builtin.include_tasks: nextcloud/apps.yml
  vars:
    nextcloud_path: "{{ nextcloud_dl_tmp_dir }}/nextcloud"

- name: "Nextcloud upgrade: upgrade via occ commandline"
  become: true
  become_user: "{{ nextcloud_http_user }}"
  ansible.builtin.command: >
    php occ upgrade
    --no-interaction
    --no-warnings
  args:
    chdir: "{{ nextcloud_dl_tmp_dir }}/nextcloud"
  changed_when: false
  notify: Test and restart apache2

- name: "Nextcloud upgrade: unset maintenance mode via occ commandline"
  become: true
  become_user: "{{ nextcloud_http_user }}"
  ansible.builtin.command: php occ maintenance:mode --off
  args:
    chdir: "{{ nextcloud_dl_tmp_dir }}/nextcloud"
  changed_when: false
