---
- name: Test and reload apache2
  ansible.builtin.command: apache2ctl configtest
  changed_when: True
  notify: Reload apache2

- name: Test and restart apache2
  ansible.builtin.command: apache2ctl configtest
  changed_when: True
  notify: Restart apache2

- name: Reload apache2
  ansible.builtin.service:
    name: apache2
    state: reloaded

- name: Restart apache2
  ansible.builtin.service:
    name: apache2
    state: restarted
  notify:
    - Restart php-fpm

- name: Restart nextcloud-notify-push
  ansible.builtin.service:
    name: nextcloud-notify-push
    state: restarted

- name: Restart php-fpm
  ansible.builtin.service:
    name: "php{{ nextcloud_php_version }}-fpm"
    state: restarted
  when: __nextcloud_php_fpm_bin and __nextcloud_php_fpm_bin.stat.exists
