---
- name: Converge
  hosts: all
  become: True
  roles:
    - role: systemli.mariadb
    - role: ansible-role-nextcloud
  vars:
    nextcloud_apache_php: False
    nextcloud_admin_password: topsecret
    nextcloud_mysql_password: topsecret
